name       : cd-discid
version    : 1.4
release    : 1
source     :
    - https://github.com/taem/cd-discid/archive/1.4.tar.gz : 6f07df25ebf17b8336c17a50092ed288cc5a6b86f85705db7e1aa35ba26683cf
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Utility to get CDDB discid information
description: |
    cd-discid is a backend utility to get CDDB discid information from a CD-ROM disc
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX%
